server:
  port: 13000
spring:
  application:
    name: config-server
  profiles:
    active: native
  config:
    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/niaonao/spring-cloud
#          username: niaonao
#          password: niaonao123456
#          default-label: master
#          search-paths: /doc/config

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
