spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: item-service
  boot:
    admin:
      client:
        url:  http://localhost:10000 #指定SpringBootAdmin服务端地址
      instance:
        name: item-service

server:
  port: 12000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
