spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: item-service

server:
  port: 12000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
